# MySQL Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/minijobboard?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

server.port=8081

# Hibernate and JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Security Configuration for Development (Default setup to simplify security development)
# We will integrate full Spring Security later
# spring.security.user.name=admin
# spring.security.user.password=admin

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=86400000
